In [1]:
# Define the documents as a dictionary where keys are document titles and values are document content
documents = {
    "Article: Pandas Basics": "This article covers the basics of using Pandas in Python.",
    "Tutorial: Data Visualization": "Learn about data visualization techniques with Python libraries.",
    "Case Study: Sales Analysis": "Analyze sales data using Python for a real-world case study."
}

In [2]:
# get the keys of the documents and store it in the list
key_documents = list(documents.keys())

# display the list of the key documents
print(key_documents)

['Article: Pandas Basics', 'Tutorial: Data Visualization', 'Case Study: Sales Analysis']


In [3]:
# Extract the category of the key documents and store it 
key_category =[key.split(':')[0].strip() for key in key_documents]
key_category

['Article', 'Tutorial', 'Case Study']

In [4]:

# Extract the content values and put them in a list
document_content_list = list(documents.values())

# Display the list of document content
print(document_content_list)

['This article covers the basics of using Pandas in Python.', 'Learn about data visualization techniques with Python libraries.', 'Analyze sales data using Python for a real-world case study.']


In [5]:
# Gather the set of all unique terms from the list content of document and diplay the result
unique_terms = {term for document in document_content_list for term in document.split()}
unique_terms

{'Analyze',
 'Learn',
 'Pandas',
 'Python',
 'Python.',
 'This',
 'a',
 'about',
 'article',
 'basics',
 'case',
 'covers',
 'data',
 'for',
 'in',
 'libraries.',
 'of',
 'real-world',
 'sales',
 'study.',
 'techniques',
 'the',
 'using',
 'visualization',
 'with'}

In [6]:
# create a matrix for the document by using the unique term
doc_term_matrix = {}

for term in unique_terms:
    doc_term_matrix[term] = []
    
    for document in documents:
        if term in document:
            doc_term_matrix[term].append(1)
        else: doc_term_matrix[term].append(0)

# display the result of the matrix
doc_term_matrix

{'Learn': [0, 0, 0],
 'sales': [0, 0, 0],
 'Pandas': [1, 0, 0],
 'the': [0, 0, 0],
 'techniques': [0, 0, 0],
 'study.': [0, 0, 0],
 'libraries.': [0, 0, 0],
 'article': [0, 0, 0],
 'in': [0, 0, 0],
 'covers': [0, 0, 0],
 'Python': [0, 0, 0],
 'This': [0, 0, 0],
 'Analyze': [0, 0, 0],
 'Python.': [0, 0, 0],
 'basics': [0, 0, 0],
 'using': [0, 0, 0],
 'case': [0, 0, 0],
 'for': [0, 0, 0],
 'visualization': [0, 0, 0],
 'about': [0, 0, 0],
 'a': [1, 1, 1],
 'of': [0, 0, 0],
 'real-world': [0, 0, 0],
 'with': [0, 0, 0],
 'data': [0, 0, 0]}

In [21]:
# import the numpy library if it doesn't work you need to install numpy
import numpy as np

docs_array = np.array(document_content_list, dtype='object')

v1 = np.array(doc_term_matrix['the'])    
v2 = np.array(doc_term_matrix['Python'])

print(v1)
print(v2)
print('-------')

# find the documents that have both terms from v1 and v2
v3 = v1 & v2

print(v3)

# display the content document from the result
[doc for doc in v3 * docs_array if doc]

[1 1 1]
[1 0 0]
-------
[1 0 0]


['This article covers the basics of using Pandas in Python.']

In [22]:
# find the document for those have at least one word
print(v1)
print(v2)
print('-------')


v4 = v1 | v2

print(v4)

[doc for doc in v4 * docs_array if doc]


[1 1 1]


['This article covers the basics of using Pandas in Python.',
 'Learn about data visualization techniques with Python libraries.',
 'Analyze sales data using Python for a real-world case study.']